 SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

BEGIN TRANSACTION;

SELECT Salary
FROM CONTRACTS
WHERE Player_ID = 1;

WAITFOR DELAY '00:00:10';

SELECT Salary
FROM CONTRACTS
WHERE Player_ID = 1;

COMMIT;
