--SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

BEGIN TRANSACTION;

SELECT
    Player_ID,
    AVG(Rating) AS AvgRating
FROM TRAINING_RATING
GROUP BY Player_ID;

COMMIT;
